### ISSUE TITLE
Is there a current document to link to on program code?

### ISSUE THREAD

**Issue by crysacarter** [GSA/resources.data.gov#70]
For program code there is not a valid link
https://resources.data.gov/schemas/dcat-us/v1.1/  (see screenshot) 

![Screen Shot 2019-10-08 at 11 13 41 AM](https://user-images.githubusercontent.com/49877323/66416008-e23fac00-e9ca-11e9-80b3-90eb500b319b.png)

**Comment by hkdctol** [comment]
@crysacarter per discussion with @rebeccawilliams yesterday, the program code will not be used going forward, but because it is still part of the schema and is required for datasets to be harvested in the catalog, for now we need to add a link to the resources.data.gov section for program code, to download the same spreadsheet that is currently downloadable at https://project-open-data.cio.gov/v1.1/schema/#programCode when you click on Federal Program Inventory

**Comment by crysacarter** [comment]
#112 - done

**Comment by hkdctol** [comment]
I think this issue can be closed. We've provided a link to the existing document, and this is a field that will be discontinued once we have the chance to do an update to the DCAT US schema.

**Comment by ktsao-usda** [comment]
I was looking for information on how to get an updated list of this program code or who the issuing authority is, then found this thread. Any timelines or documentation on when/why the field will be discontinued? In the meantime, should the (Primary Program Not Available) value be specified if the appropriate program is not listed? Thanks and apologies if this question should be directed elsewhere.

**Comment by hkdctol** [comment]
Hi--I don't have the background on how/why use was discontinued--that would be an OMB question. I still think when there is a schema update (which is awaiting issuance of OMB guidance on it) that it will be eliminated as a required field.
